try:
    # x = 6
    print(x)
except:
    print("An error occurred")

finally:
    print("successful")
